// src/models/notifications.model.ts

export interface Notification {
  id?: string;          // UUID Primary Key (auto-generated by Supabase)
  content: string;
  title: string;
  user_id: string;      // UUID reference to your users table
  is_read: boolean;     // Maps to your 'isRead' field
  created_at?: string;  // Replaces Mongoose 'timestamps'
  updated_at?: string;
}